### ISSUE TITLE
Can't leave the round.

### ISSUE THREAD

**Issue by Qugar** [Owen3H/CSync#2]
Once I have loaded a save game, I can no longer exit the game. This error message follows:

![grafik](https://github.com/Owen3H/CSync/assets/8191849/a4442732-2db9-4c16-b4fc-70283dd8e0fd)

**Comment by Owen3H** [comment]
This should only occur if the user has CSync v2, but the author has not migrated and so these methods aren't available.
The usage changed quite a bit (in a good way) and devs are recommended to update :)

For now, it's probably safe to stay on 1.0.8 until they do.
