### ISSUE TITLE
[Suggestion] Event for RevertSync too

### ISSUE THREAD

**Issue by SylviBlossom** [Owen3H/CSync#3]
pre-2.0.0 boilerplate code I use for one of my mods calls a function to update static values both after syncing and unsyncing, so having a callback for it would be helpful

**Comment by Owen3H** [comment]
Good idea, don't know how I missed that.

**Comment by Owen3H** [comment]
Should be done with 0bc39b7054d7176ac2274919b95aa6192d29f7c6 and will be in the next version.

**Comment by Owen3H** [comment]
Added in [v2.1.0](https://thunderstore.io/c/lethal-company/p/Owen3H/CSync/changelog/) which was just released.
